
from math import log

OMEGA = log(7,2)

PRECISION_EPS = 3
SCALE_PRECISION_EPS = 10**PRECISION_EPS
PRECISION_DELTA = 3
SCALE_PRECISION_DELTA = 10**PRECISION_DELTA
MAX_LOG_EPS = 256

DATA_SCALE=2 # Scale the data complexity

MAX_PRECOMPUTED_COEFFS = 6500
